/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TagPagePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/utils/tagSearch.ts
var getIsWildCard = (tag) => {
  const isWildCard = tag.endsWith("/*");
  const cleanedTag = isWildCard ? tag.slice(0, -2) : tag;
  return { isWildCard, cleanedTag };
};
var containsTag = (stringToSearch, tag) => {
  const { isWildCard, cleanedTag } = getIsWildCard(tag);
  const lowerStringToSearch = stringToSearch.toLowerCase();
  const lowerCleanedTag = cleanedTag.toLowerCase();
  const escapedTag = lowerCleanedTag.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  if (isWildCard) {
    return lowerStringToSearch.includes(lowerCleanedTag);
  } else {
    const boundaryLookahead = "(?=$|\\s|[.,;:!?\"'`<>()\\[\\]{}_-])";
    const regex = new RegExp(`${escapedTag}${boundaryLookahead}`, "i");
    return regex.test(lowerStringToSearch);
  }
};
var findSmallestUnitsContainingTag = (content, tag, excludeBullets = false) => {
  const { isWildCard, cleanedTag } = getIsWildCard(tag);
  const escapedSubstring = cleanedTag.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const wildcardPattern = isWildCard ? "(?:\\/[\\S]+)*" : "";
  const contentLines = content.split("\n").filter((line) => !(excludeBullets && line.trim().startsWith("-")));
  const matchesMap = /* @__PURE__ */ new Map();
  contentLines.forEach((line) => {
    const regex = new RegExp(`${escapedSubstring}${wildcardPattern}`, "gi");
    const matches = [...line.matchAll(regex)];
    matches.forEach((match) => {
      let key = match[0].toLowerCase();
      if (isWildCard && key.endsWith("/*")) {
        key = key.slice(0, -2);
      }
      if (!matchesMap.has(key)) {
        matchesMap.set(key, [line.trim()]);
      } else {
        const existingLines = matchesMap.get(key);
        if (!existingLines.includes(line.trim())) {
          existingLines.push(line.trim());
        }
      }
    });
  });
  return matchesMap;
};
var findBulletListsContainingTag = (content, tag) => {
  const capturedBulletLists = /* @__PURE__ */ new Map();
  const fileLines = content.split("\n").filter((line) => line.trim() !== "");
  let currentBulletIndentation = 0;
  const lastTagsAtCurrentIndentation = /* @__PURE__ */ new Set();
  let capturingSubBullet = false;
  fileLines.forEach((line) => {
    const lineTrim = line.trim();
    const startsWithBullet = lineTrim.startsWith("- ");
    const lineIndentation = line.search(/\S/);
    if (startsWithBullet) {
      const { isWildCard, cleanedTag } = getIsWildCard(tag);
      const tagRegex = isWildCard ? `${cleanedTag}(?:/[^\\s]+)*` : `${cleanedTag}(?![^\\s])`;
      const regex = new RegExp(tagRegex, "gi");
      const matches = line.match(regex);
      if (startsWithBullet && (matches || lineIndentation <= currentBulletIndentation)) {
        capturingSubBullet = false;
        currentBulletIndentation = lineIndentation;
        lastTagsAtCurrentIndentation.clear();
      }
      if (matches) {
        capturingSubBullet = false;
        matches.forEach((match) => {
          var _a;
          const trimmedMatch = isWildCard && match.endsWith("/") ? match.slice(0, -1) : match;
          const trimmedMatchLowerCase = trimmedMatch.toLowerCase();
          if (!capturedBulletLists.has(trimmedMatchLowerCase)) {
            capturedBulletLists.set(trimmedMatchLowerCase, []);
          }
          (_a = capturedBulletLists.get(trimmedMatchLowerCase)) == null ? void 0 : _a.push(
            lineIndentation > currentBulletIndentation && capturingSubBullet ? line : lineTrim
          );
          lastTagsAtCurrentIndentation.add(trimmedMatchLowerCase);
        });
      } else if (lineIndentation > currentBulletIndentation && lastTagsAtCurrentIndentation.size > 0) {
        capturingSubBullet = true;
        lastTagsAtCurrentIndentation.forEach((tag2) => {
          var _a;
          (_a = capturedBulletLists.get(tag2)) == null ? void 0 : _a.push(line);
        });
      }
    }
  });
  return capturedBulletLists;
};
function consolidateTagInfo(fileInfo, unitsContainingTag, bulletListsContainingTag) {
  const consolidatedInfo = /* @__PURE__ */ new Map();
  const addMatchesToConsolidatedInfo = (tag, matches) => {
    const existingMatches = consolidatedInfo.get(tag) || [];
    const newMatches = matches.map((matchString) => ({
      ...fileInfo,
      stringContainingTag: matchString
    }));
    consolidatedInfo.set(tag, existingMatches.concat(newMatches));
  };
  unitsContainingTag == null ? void 0 : unitsContainingTag.forEach((matches, tag) => {
    addMatchesToConsolidatedInfo(tag, matches);
  });
  bulletListsContainingTag == null ? void 0 : bulletListsContainingTag.forEach((matches, tag) => {
    addMatchesToConsolidatedInfo(tag, matches);
  });
  return consolidatedInfo;
}
var processFile = async (vault, settings, file, tagOfInterest) => {
  const fileContents = await vault.cachedRead(file);
  if (!containsTag(fileContents, tagOfInterest))
    return /* @__PURE__ */ new Map();
  const fileLink = settings.fullLinkName ? `[[${file.basename}]]` : `[[${file.basename}|*]]`;
  const fileInfo = {
    fileLink,
    timestamp: file.stat.ctime,
    sourcePath: file.path
  };
  switch (true) {
    case (settings.bulletedSubItems && settings.includeLines):
      return consolidateTagInfo(
        fileInfo,
        findSmallestUnitsContainingTag(
          fileContents,
          tagOfInterest,
          true
        ),
        findBulletListsContainingTag(fileContents, tagOfInterest)
      );
    case (settings.bulletedSubItems && !settings.includeLines):
      return consolidateTagInfo(
        fileInfo,
        void 0,
        findBulletListsContainingTag(fileContents, tagOfInterest)
      );
    case (!settings.bulletedSubItems && settings.includeLines):
    default:
      return consolidateTagInfo(
        fileInfo,
        findSmallestUnitsContainingTag(
          fileContents,
          tagOfInterest,
          false
        ),
        void 0
      );
  }
};
var fetchTagData = async (app, settings, tagOfInterest) => {
  const vault = app.vault;
  const allFiles = vault.getMarkdownFiles();
  const tagDirPrefix = settings.tagPageDir.endsWith("/") ? settings.tagPageDir : `${settings.tagPageDir}/`;
  return await Promise.all(
    allFiles.filter((file) => !file.path.startsWith(tagDirPrefix)).map((file) => processFile(vault, settings, file, tagOfInterest))
  ).then((tagInfos) => {
    const consolidatedTagInfo = /* @__PURE__ */ new Map();
    tagInfos.forEach((tagInfo) => {
      tagInfo.forEach((details, tag) => {
        const existingDetails = consolidatedTagInfo.get(tag) || [];
        const combinedDetails = existingDetails.concat(details);
        if (settings.sortByDate === "desc" /* DESC */) {
          combinedDetails.sort((a, b) => b.timestamp - a.timestamp);
        } else {
          combinedDetails.sort((a, b) => a.timestamp - b.timestamp);
        }
        consolidatedTagInfo.set(tag, combinedDetails);
      });
    });
    return consolidatedTagInfo;
  });
};

// src/utils/pageContent.ts
var import_obsidian = require("obsidian");
var path = __toESM(require("path"));
var generateTagPageContent = async (app, settings, tagsInfo, tagOfInterest) => {
  const tagPageContent = [];
  tagPageContent.push(resolveTagPageTitle(settings, tagOfInterest));
  if (tagsInfo.size > 1) {
    const sortedTagsInfo = Array.from(tagsInfo).sort((a, b) => {
      return a[0].length - b[0].length;
    });
    sortedTagsInfo.forEach(([baseTag, details]) => {
      tagPageContent.push(`### ${baseTag}`);
      details.forEach(({ stringContainingTag, fileLink, sourcePath }) => {
        processTagMatch(
          stringContainingTag,
          fileLink,
          sourcePath,
          tagPageContent,
          settings.linkAtEnd,
          app
        );
      });
    });
  } else {
    tagsInfo.forEach((details) => {
      details.forEach(({ stringContainingTag, fileLink, sourcePath }) => {
        processTagMatch(
          stringContainingTag,
          fileLink,
          sourcePath,
          tagPageContent,
          settings.linkAtEnd,
          app
        );
      });
    });
  }
  const filesWithFrontmatterTag = app.vault.getMarkdownFiles().filter((file) => {
    var _a;
    const metaMatter = (_a = app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
    return (metaMatter == null ? void 0 : metaMatter.tags) ? matchesTagOfInterest(metaMatter.tags, tagOfInterest) : false;
  }).map((file) => `- [[${file.basename}]]`);
  if (filesWithFrontmatterTag.length > 0) {
    const { cleanedTag } = getIsWildCard(tagOfInterest);
    tagPageContent.push(`## Files with ${cleanedTag} in frontmatter`);
    tagPageContent.push(...filesWithFrontmatterTag);
  }
  return tagPageContent.join("\n");
};
function processTagMatch(fullTag, fileLink, sourcePath, tagPageContent, linkAtEnd, app) {
  const resolvedTag = resolveRelativeEmbeds(app, sourcePath, fullTag);
  if (resolvedTag.trim().startsWith("-")) {
    const [firstBullet, ...bullets] = resolvedTag.split("\n");
    const firstBulletIndent = firstBullet.match(/^(\s*)-/);
    if (firstBulletIndent && firstBulletIndent[1].length > 0) {
      tagPageContent.push(resolvedTag);
      return;
    }
    const bulletMatch = firstBullet.match(/^(\s*-\s*)(.*)$/);
    if (linkAtEnd) {
      const firstBulletWithLink = `${firstBullet} ${fileLink}`;
      tagPageContent.push([firstBulletWithLink, ...bullets].join("\n"));
    } else if (bulletMatch) {
      const [, prefix, rest] = bulletMatch;
      const firstLine = `${prefix}${fileLink} ${rest}`.trimEnd();
      tagPageContent.push([firstLine, ...bullets].join("\n"));
    } else {
      const firstLine = `${fileLink} ${firstBullet}`.trimEnd();
      tagPageContent.push([firstLine, ...bullets].join("\n"));
    }
  } else {
    const content = linkAtEnd ? `- ${resolvedTag} ${fileLink}` : `- ${fileLink} ${resolvedTag}`;
    tagPageContent.push(content.trimEnd());
  }
}
function resolveRelativeEmbeds(app, sourcePath, content) {
  const withResolvedWikiEmbeds = content.replace(
    /!\[\[([^\]]+)\]\]/g,
    (match, inner) => {
      var _a, _b;
      const [linkTarget, alias] = inner.split("|", 2);
      const parsed = linkTarget.match(/^([^#^]+)([#^].+)?$/);
      const baseTarget = (_a = parsed == null ? void 0 : parsed[1]) != null ? _a : linkTarget;
      const suffix = (_b = parsed == null ? void 0 : parsed[2]) != null ? _b : "";
      const resolved = app.metadataCache.getFirstLinkpathDest(
        baseTarget,
        sourcePath
      );
      if (!resolved)
        return match;
      const resolvedTarget = `${resolved.path}${suffix}`;
      const aliasSuffix = alias ? `|${alias}` : "";
      return `![[${resolvedTarget}${aliasSuffix}]]`;
    }
  );
  return withResolvedWikiEmbeds.replace(
    /!\[([^\]]*)\]\(([^)]+)\)/g,
    (match, altText, rawUrl) => {
      const url = rawUrl.trim().replace(/^<|>$/g, "");
      if (/^[a-z]+:|^#/i.test(url))
        return match;
      const resolved = app.metadataCache.getFirstLinkpathDest(
        url,
        sourcePath
      );
      if (resolved) {
        return `![${altText}](${resolved.path})`;
      }
      const baseDir = path.posix.dirname(sourcePath);
      const joined = (0, import_obsidian.normalizePath)(path.posix.join(baseDir, url));
      return `![${altText}](${joined})`;
    }
  );
}
function matchesTagOfInterest(tags, tagOfInterest) {
  const normalizedTags = Array.isArray(tags) ? tags : [tags];
  const { isWildCard, cleanedTag: tagBase } = getIsWildCard(tagOfInterest);
  if (isWildCard) {
    return normalizedTags.some((tag) => {
      const fullTag = `#${tag}`;
      return fullTag === tagBase || fullTag.startsWith(`${tagBase}/`);
    });
  } else {
    return normalizedTags.some((tag) => `#${tag}` === tagBase);
  }
}
var generateFilename = (cleanedTag, isWildCard, nestedSeparator) => {
  return `${cleanedTag.replace("#", "").replaceAll("/", nestedSeparator)}${isWildCard ? nestedSeparator + "nested" : ""}${nestedSeparator}Tags.md`;
};
var resolveTagPageTitle = (settings, tagOfInterest) => {
  const template = settings.tagPageTitleTemplate;
  if (!template) {
    return `## Tag Content for ${tagOfInterest.replace("*", "")}`;
  } else {
    const tag = `${tagOfInterest.replace("*", "")}`;
    const tagName = `${tagOfInterest.replace("*", "")}`.replace("#", "");
    return "## " + template.replaceAll("{{lf}}", "\n").replaceAll("{{tag}}", " " + tag).replaceAll("{{tagname}}", tagName).replaceAll("  ", " ");
  }
};

// main.ts
var DEFAULT_SETTINGS = {
  tagPageDir: "Tags/",
  sortByDate: "desc" /* DESC */,
  nestedSeparator: "_",
  tagPageTitleTemplate: "Tag Content for {{tag}}",
  bulletedSubItems: true,
  includeLines: true,
  fullLinkName: false,
  linkAtEnd: true,
  legacyFrontmatterQueryProperty: "tag-page-query"
};
var _TagPagePlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.legacyMigrationInProgress = /* @__PURE__ */ new Set();
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new TagPageSettingTab(this.app, this));
    this.addCommand({
      id: "create-tag-page",
      name: "Create tag page",
      callback: () => {
        new CreateTagPageModal(this.app, this).open();
      }
    });
    this.addCommand({
      id: "cleanup-legacy-tag-page",
      name: "Clean up legacy tag page content",
      callback: () => {
        this.cleanupLegacyTagPageContent();
      }
    });
    this.registerMarkdownCodeBlockProcessor(
      "tag-page",
      (source, el, ctx) => {
        this.renderTagPageBlock(source, el, ctx.sourcePath);
      }
    );
    this.registerEvent(
      this.app.workspace.on("file-open", (file) => {
        if (file) {
          void this.migrateLegacyTagPage(file);
        }
      })
    );
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /**
   * Creates a new tag page or navigates to an existing one.
   *
   * @param {string} tag - The tag for which to create or navigate to a page.
   * @returns {Promise<void>} - A promise that resolves when the operation is complete.
   */
  async createTagPage(tag) {
    const tagOfInterest = tag.startsWith("#") ? tag : `#${tag}`;
    const { isWildCard, cleanedTag } = getIsWildCard(tagOfInterest);
    const filename = generateFilename(
      cleanedTag,
      isWildCard,
      this.settings.nestedSeparator
    );
    const tagPage = this.app.vault.getAbstractFileByPath(
      `${this.settings.tagPageDir}${filename}`
    );
    if (!tagPage) {
      const exists = await this.app.vault.adapter.exists(
        (0, import_obsidian2.normalizePath)(this.settings.tagPageDir)
      );
      if (!exists) {
        await this.app.vault.createFolder(this.settings.tagPageDir);
      }
      const tagPageContentString = this.buildTagPageTemplate(tagOfInterest);
      const createdPage = await this.app.vault.create(
        `${this.settings.tagPageDir}${filename}`,
        tagPageContentString
      );
      await this.app.workspace.getLeaf().openFile(createdPage);
    } else {
      await this.app.workspace.getLeaf().openFile(tagPage);
    }
  }
  /**
   * Renders the markdown code block tagged as `tag-page`.
   *
   * @param source - The content of the code block.
   * @param el - The target element for rendering the generated content.
   * @param sourcePath - The path of the note containing the block, used to resolve relative links.
   */
  async renderTagPageBlock(source, el, sourcePath) {
    const tags = this.parseTagsFromBlock(source);
    if (tags.length === 0) {
      el.createEl("p", {
        text: "No tags provided. Add `tags: #tag` inside the tag-page code block."
      });
      return;
    }
    const container = el.createDiv({ cls: "tag-page-block" });
    for (const tag of tags) {
      const tagSection = container.createDiv({
        cls: "tag-page-block__section"
      });
      const loadingState = tagSection.createEl("p", {
        text: `Loading content for ${tag}...`
      });
      try {
        const tagsInfo = await fetchTagData(
          this.app,
          this.settings,
          tag
        );
        const markdown = await generateTagPageContent(
          this.app,
          this.settings,
          tagsInfo,
          tag
        );
        tagSection.empty();
        await import_obsidian2.MarkdownRenderer.render(
          this.app,
          markdown,
          tagSection,
          sourcePath,
          this
        );
      } catch (error) {
        console.error(error);
        tagSection.empty();
        tagSection.createEl("p", {
          text: `Failed to render tag page for ${tag}.`
        });
      } finally {
        loadingState.remove();
      }
    }
  }
  buildTagPageTemplate(tagOfInterest) {
    const lines = [
      "```tag-page",
      `tags: ${tagOfInterest}`,
      "```",
      ""
    ];
    return lines.join("\n");
  }
  parseTagsFromBlock(source) {
    const tagsLine = source.split("\n").map((line) => line.trim()).find((line) => line.toLowerCase().startsWith("tags:"));
    if (!tagsLine)
      return [];
    const tags = tagsLine.slice("tags:".length).split(/\s+/).map((tag) => tag.trim()).filter(Boolean).map((tag) => tag.startsWith("#") ? tag : `#${tag}`);
    return Array.from(new Set(tags));
  }
  getLegacyFrontmatterKey() {
    return this.settings.legacyFrontmatterQueryProperty || "tag-page-query";
  }
  normalizeLegacyTags(rawTags) {
    const tags = Array.isArray(rawTags) ? rawTags : String(rawTags).split(/[,\s]+/).filter(Boolean);
    return Array.from(
      new Set(tags.map((tag) => tag.startsWith("#") ? tag : `#${tag}`))
    );
  }
  async migrateLegacyTagPage(file) {
    var _a, _b;
    const filePath = file.path;
    if (this.legacyMigrationInProgress.has(filePath))
      return;
    const legacyKey = this.getLegacyFrontmatterKey();
    const frontmatterValue = (_b = (_a = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter) == null ? void 0 : _b[legacyKey];
    if (!frontmatterValue)
      return;
    try {
      this.legacyMigrationInProgress.add(filePath);
      const content = await this.app.vault.read(file);
      if (/```tag-page[\s\S]*?```/i.test(content) || content.includes(_TagPagePlugin.LEGACY_CONTENT_MARKER)) {
        return;
      }
      const tags = this.normalizeLegacyTags(frontmatterValue);
      if (tags.length === 0)
        return;
      const block = [
        "```tag-page",
        `tags: ${tags.join(" ")}`,
        "```",
        ""
      ].join("\n");
      const frontmatterMatch = content.match(/^---\n[\s\S]*?\n---\n?/);
      const nextContent = frontmatterMatch ? content.replace(
        frontmatterMatch[0],
        `${frontmatterMatch[0]}
${block}${_TagPagePlugin.LEGACY_CONTENT_MARKER}
`
      ) : `${block}${_TagPagePlugin.LEGACY_CONTENT_MARKER}
${content}`;
      await this.app.vault.modify(file, nextContent);
      await this.maybeShowLegacyMigrationNotice();
    } finally {
      this.legacyMigrationInProgress.delete(filePath);
    }
  }
  async cleanupLegacyTagPageContent() {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      new import_obsidian2.Notice("Tag Page: no active file to clean up.");
      return;
    }
    const content = await this.app.vault.read(activeFile);
    const markerIndex = content.indexOf(
      _TagPagePlugin.LEGACY_CONTENT_MARKER
    );
    if (markerIndex === -1) {
      new import_obsidian2.Notice("Tag Page: no legacy marker found in this note.");
      return;
    }
    const nextContent = content.slice(0, markerIndex).replace(/\s*$/, "\n");
    await this.app.vault.modify(activeFile, nextContent);
    new import_obsidian2.Notice("Tag Page: legacy content removed.");
  }
  async maybeShowLegacyMigrationNotice() {
    new import_obsidian2.Notice(
      'Tag Page: added a tag-page code block to migrate this note. Run "Clean up legacy tag page content" when ready.'
    );
  }
};
var TagPagePlugin = _TagPagePlugin;
TagPagePlugin.LEGACY_CONTENT_MARKER = "<!-- tag-page-legacy-content -->";
var CreateTagPageModal = class extends import_obsidian2.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    var _a, _b;
    const { contentEl } = this;
    contentEl.setText("Tag to create page for:");
    const tagForm = contentEl.createEl("form");
    contentEl.addClass("create-page-modal");
    const allTagsRecord = (
      // @ts-ignore - getTags is available at runtime but not in type defs
      ((_b = (_a = this.app.metadataCache).getTags) == null ? void 0 : _b.call(_a)) || {}
    );
    const existingTags = Object.keys(allTagsRecord).sort(
      (a, b) => a.localeCompare(b)
    );
    const datalistId = "tag-page-suggestions";
    if (existingTags.length > 0) {
      const datalist = contentEl.createEl("datalist", {
        attr: { id: datalistId }
      });
      existingTags.forEach((tag) => {
        datalist.createEl("option", {
          attr: { value: tag.startsWith("#") ? tag : `#${tag}` }
        });
      });
    }
    const input = tagForm.createEl("input", { type: "text" });
    input.placeholder = "#tag";
    input.value = "#";
    if (existingTags.length > 0) {
      input.setAttr("list", datalistId);
    }
    input.addEventListener("keydown", (e) => {
      const cursorPosition = input.selectionStart;
      if (cursorPosition === 1 && (e.key === "Backspace" || e.key === "Delete")) {
        e.preventDefault();
      }
    });
    const submitButton = tagForm.createEl("button", { type: "submit" });
    submitButton.innerText = "Create Tag Page";
    tagForm.addEventListener("submit", async (e) => {
      e.preventDefault();
      const tag = input.value;
      this.contentEl.empty();
      this.contentEl.setText(`Creating tag page for ${tag}...`);
      await this.plugin.createTagPage(tag);
      this.close();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var TagPageSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("Tag page directory").setDesc("The directory in which to create tag pages.").addText(
      (text) => text.setValue(this.plugin.settings.tagPageDir).onChange(async (value) => {
        if (!value.endsWith("/")) {
          value = `${value}/`;
        }
        this.plugin.settings.tagPageDir = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Sort content by Date").setDesc(
      "Designate whether the content should be sorted in descending or ascending order. Defaults to descending (newest content first)."
    ).addDropdown(
      (component) => component.addOption("desc" /* DESC */, "Descending").addOption("asc" /* ASC */, "Ascending").setValue("desc" /* DESC */).onChange(async (value) => {
        this.plugin.settings.sortByDate = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Nested page separator").setDesc(
      `Text used to separate levels for nested tags. Avoid \\/<>:"|?* and other characters that aren't file-safe, or you won't be able to make pages for nested tags.`
    ).addText(
      (text) => text.setValue(this.plugin.settings.nestedSeparator).onChange(async (value) => {
        this.plugin.settings.nestedSeparator = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Tag page title template").setDesc(
      "Title template for the tag page. The placeholder '{{tag}}' will be replaced by the actual tag. The placeholder '{{tagname}}' will be replaced by just the tag name (without the '#' symbol and without a link). The placeholder '{{lf}}' (line feed) is used to add new lines for optional spacing or to insert static text between the title and the tags."
    ).addText(
      (text) => text.setValue(this.plugin.settings.tagPageTitleTemplate).onChange(async (value) => {
        this.plugin.settings.tagPageTitleTemplate = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Include lines").setDesc("Include lines containing the tag in the tag page.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.includeLines).onChange(async (value) => {
        this.plugin.settings.includeLines = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Bulleted sub-items").setDesc(
      "Include bulleted sub-items containing the tag in the tag page."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.bulletedSubItems).onChange(async (value) => {
        this.plugin.settings.bulletedSubItems = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Display full link name as reference").setDesc(
      "Each bit of pulled content will display the full link title as a reference as an end of line. Displays * when false."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.fullLinkName).onChange(async (value) => {
        this.plugin.settings.fullLinkName = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Legacy frontmatter key").setDesc(
      "Used to detect old tag pages and auto-insert a tag-page block for migration."
    ).addText(
      (text) => text.setPlaceholder("tag-page-query").setValue(
        this.plugin.settings.legacyFrontmatterQueryProperty || ""
      ).onChange(async (value) => {
        this.plugin.settings.legacyFrontmatterQueryProperty = value.trim() || "tag-page-query";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Link position").setDesc(
      "Choose whether the reference link appears at the end (default) or start of each pulled line."
    ).addDropdown(
      (dropdown) => dropdown.addOption("end", "End of line").addOption("start", "Start of line").setValue(this.plugin.settings.linkAtEnd ? "end" : "start").onChange(async (value) => {
        this.plugin.settings.linkAtEnd = value === "end";
        await this.plugin.saveSettings();
      })
    );
  }
};

/* nosourcemap */