[Folder Decks]
; Map vault-relative path regexes to Anki deck names. First match wins.
; Example: Docs/Programming_and_OS/Cpp = Cpp
Docs/Programming_and_OS/C = C
Docs/Programming_and_OS/Python = Python
Docs/Programming_and_OS/Rust = Rust
Docs/Programming_and_OS/Docker = Docker
Docs/Programming_and_OS/Go = Go
Docs/Programming_and_OS/SQL = SQL
Docs/Networks_Signals_Protocols/.* = Networking
Docs/Programming_and_OS/GNU.* = Linux/GNU
Docs/.* = Default

[Custom Regexps]
Code = ^ (.*?) ;;; (.*?)
Term = ^󰙎 (.*?) ;;; (.*?)
Quiz = ^󰠗  (.*?) ;; (.*?)

[Syntax]
Begin Note = START
End Note = END
Begin Inline Note = STARTI
End Inline Note = ENDI
Target Deck Line = TARGET DECK
File Tags Line = FILE TAGS
Delete Regex Note Line = DELETE
Frozen Fields Line = FROZEN
Delete Note Line = DELETE

[Obsidian]
Vault path = /home/will/Documents/Obsidian_vaults/Work
Add file link = True

[Defaults]
Tag = Obsidian_to_Anki
Deck = Default
CurlyCloze = False
Regex = True
ID Comments = True
Anki Path = /mnt/c/Users/willg/AppData/Local/Programs/Anki/anki.exe
Anki Profile = User 1

